export type ServiceDetail = {
  slug: string;
  title: string;
  subtitle: string;
  icon: string;
  shortDesc: string;
  overview: string;
  quote: string;
  documents?: { name: string; desc: string }[];
  whatWeDo: string[];
  process: { step: string; title: string; desc: string }[];
  timeline: string;
  docsRequired: string[];
};

export const services: ServiceDetail[] = [
  {
    slug: "title-search-due-diligence",
    title: "Title Search & Due Diligence",
    subtitle: "Ownership Verification · Encumbrance Search · Legal Opinion · Pre-Purchase Advisory",
    icon: "🔍",
    shortDesc: "Thorough title search reports and property due diligence — including scrutiny of ownership chain, encumbrance verification, stamp duty guidance, and pre-execution legal opinion to prevent disputes.",
    overview: "A property may appear flawless in location, structure, or market value — yet without a legally sound title, even the most attractive deal can collapse under litigation.\n\nTitle due diligence is the single most critical step before any property investment. It answers the fundamental question: does the seller truly own what they are selling — and can they legally transfer it to you?\n\nWith 24 years of practice in property law, Advocate Anirudh Kamble provides comprehensive title search reports and due diligence that give you complete clarity on a property's legal status before you commit.",
    quote: "Let the buyer beware — but let the buyer also be advised. A clean title confirmed today is the best investment protection tomorrow.",
    whatWeDo: [
      "Title chain examination for minimum 30 years",
      "Encumbrance Certificate analysis and interpretation",
      "7/12 Extract and Property Card verification",
      "Search for litigation, court orders, and injunctions",
      "RERA compliance verification for under-construction projects",
      "Comprehensive written Title Search Report / Legal Opinion",
    ],
    process: [
      { step: "01", title: "Document Collection", desc: "We collect and review all available title documents, including prior Sale Deeds, Agreements, Gift Deeds, and any other instruments forming part of the title chain." },
      { step: "02", title: "Government Records Search", desc: "We conduct searches at the Sub-Registrar's office, obtain the Encumbrance Certificate, and verify the property records with the 7/12 Extract or City Survey records." },
      { step: "03", title: "Litigation & Encumbrance Check", desc: "We search for any pending litigation, court orders, government acquisition notices, or attachments that may affect the property or the seller's title." },
      { step: "04", title: "Analysis & Report Preparation", desc: "All findings are analysed and compiled into a comprehensive Title Search Report — clearly setting out the title history, any issues found, and our legal opinion on the safety of the transaction." },
      { step: "05", title: "Advisory & Recommendations", desc: "We present our findings to you, explain any concerns in plain language, and advise on any conditions, rectifications, or additional safeguards recommended before proceeding." },
    ],
    timeline: "Standard Title Search Report: 5–10 working days. Complex or rural properties with longer title chains may require additional time.",
    docsRequired: [
      "All available title documents provided by the seller",
      "Survey number / CTS number / Property details",
      "7/12 Extract or Property Card (if available)",
      "Prior sale deeds and agreements (as many as available)",
      "Encumbrance Certificate (we obtain this independently)",
    ],
  },,
  {
    slug: "property-documentation-registration",
    title: "Property Documentation & Registration",
    subtitle: "Agreement to Sale · Sale Deed · Gift Deed · Lease Deed · Leave & License · Power of Attorney · Apartment Deed · Deed of Declaration · Deemed Conveyance · Title Search",
    icon: "📄",
    shortDesc: "Agreement to Sale, Sale Deed, Gift Deed, Lease Deed, Leave & License Agreements, Power of Attorney, Apartment Deed — all drafted with legal precision and registered before the Sub-Registrar Office.",
    overview: "Property documentation is the legal backbone of any real estate transaction. Whether you are purchasing a flat in a housing society, gifting a plot to a family member, or entering into a leave and license arrangement for a commercial space, the documents that govern these transactions must be drafted with absolute legal precision.\n\nIn Maharashtra, property documents must comply with the Registration Act, 1908, the Maharashtra Stamp Act, and various state-specific regulations. A document that is improperly drafted — even by a small margin — can result in disputes, financial loss, or challenges to your ownership years after the transaction is complete.\n\nWith over 24 years of dedicated practice, Advocate Anirudh Kamble offers comprehensive, end-to-end legal assistance covering the preparation, vetting, and registration of all property documents before the Sub-Registrar Office in Pune and Pimpri Chinchwad.",
    quote: "In property law, the strength of your documentation is the strength of your ownership. We ensure yours is unassailable.",
    documents: [
      { name: "Agreement to Sale", desc: "The foundational document in any property purchase. Records the terms agreed upon between buyer and seller — including the sale consideration, possession timeline, and conditions precedent. Protects the buyer's advance payment and clearly defines the path to the final Sale Deed." },
      { name: "Sale Deed", desc: "The primary document by which ownership of immovable property is legally transferred from seller to buyer. Must be compulsorily registered and supported by accurate stamp duty calculations. We ensure the Sale Deed correctly reflects the title, consideration, boundary details, and all encumbrance clearances." },
      { name: "Gift Deed", desc: "Enables the transfer of property to a family member or other person without monetary consideration. Must be properly drafted, stamped at applicable rates, and registered. We handle the entire process, including guidance on stamp duty benefits for gifts within family relationships." },
      { name: "Lease Deed", desc: "Governs long-term tenancy arrangements typically for periods exceeding 12 months. Must be compulsorily registered. Defines rights and obligations of both landlord and tenant, including rent, deposit, permitted use, and conditions for renewal or termination." },
      { name: "Leave & License Agreement", desc: "The legally preferred instrument for residential and commercial lettings in Maharashtra. Clearly establishes the licensor-licensee relationship, offers better protection to the property owner, and is registered online through the Maharashtra government's iSarita portal." },
      { name: "Power of Attorney", desc: "Authorises a trusted individual to act on your behalf in property matters. Especially important for NRIs, senior citizens, or parties who cannot be physically present. We draft General and Special POAs tailored to the exact scope of authority required." },
      { name: "Apartment Deed & Deed of Declaration", desc: "Under MOFA, an Apartment Deed records individual ownership of a flat along with the proportionate undivided share in land and common areas. A Deed of Declaration is executed by the promoter/developer declaring the details of the scheme." },
      { name: "Deemed Conveyance", desc: "Many housing societies in Pune have not received conveyance of land and building from the original developer. Through the Deemed Conveyance process, the society can obtain legal title even without the developer's cooperation. We assist societies through the entire process — from application to final registration." },
    ],
    whatWeDo: [
      "Drafting and vetting of all property documents",
      "Accurate stamp duty calculation and payment guidance",
      "Title search and encumbrance verification",
      "End-to-end registration at Sub-Registrar Office",
      "Guidance on RERA compliance for under-construction projects",
      "Assistance with 7/12 Extract, Property Card, and mutation",
    ],
    process: [
      { step: "01", title: "Initial Consultation & Document Review", desc: "We begin by understanding the nature of your transaction and reviewing existing title documents, prior agreements, and property records. This helps identify any issues that need resolution before documentation proceeds." },
      { step: "02", title: "Title Search & Due Diligence", desc: "We conduct a thorough search of the title chain to verify ownership, check for encumbrances, mortgages, or litigation, and confirm that the seller has clear and marketable title to transfer." },
      { step: "03", title: "Stamp Duty Assessment & Guidance", desc: "We calculate the applicable stamp duty under the Maharashtra Stamp Act, advise on any exemptions available, and ensure the document is properly e-stamped before execution." },
      { step: "04", title: "Drafting of the Document", desc: "The document is drafted with meticulous attention to legal requirements, the specific terms agreed between the parties, and provisions that protect your long-term interests." },
      { step: "05", title: "Client Review & Finalisation", desc: "The draft is shared with you for review. We explain every clause in plain language, accommodate your questions, and make any agreed revisions before finalisation." },
      { step: "06", title: "Registration at Sub-Registrar Office", desc: "We accompany you to the Sub-Registrar Office, ensure all formalities are completed, and facilitate the registration of the document — returning you a certified copy for your records." },
    ],
    timeline: "Typically 3–7 working days for standard documents. Deemed Conveyance proceedings may take 3–6 months depending on the Competent Authority's schedule.",
    docsRequired: [
      "Identity proof of all parties (Aadhaar, PAN, Passport)",
      "Photographs of buyer, seller, and two witnesses",
      "7/12 Extract or Property Card",
      "Encumbrance Certificate (last 30 years)",
      "Prior title documents / chain documents",
      "Society NOC (for resale flats)",
      "RERA registration details (for under-construction projects)",
      "TDS receipt (Form 26QB) if property value > ₹50 lakhs",
    ],
  },,
  {
    slug: "contract-commercial-drafting",
    title: "Contract & Commercial Drafting",
    subtitle: "Development Agreements · Joint Ventures · Service Agreements · MOU · NDA · Loan & Mortgage · Partnership · Employment",
    icon: "✍️",
    shortDesc: "Professionally drafted contracts for individuals, businesses, and developers. MOU, Deed of Assignment, and tailored commercial agreements ensuring enforceability and protection of interests.",
    overview: "A contract is only as strong as the words it contains. Vague language, missing clauses, or legally unenforceable terms can turn a routine business arrangement into a costly dispute.\n\nWith over 24 years of legal practice, Advocate Anirudh Kamble provides meticulous contract drafting and MOU preparation — ensuring your agreements are precise, compliant with applicable law, and enforceable in court. We draft contracts for individuals, businesses, developers, and institutions across a wide range of commercial and property-related transactions.",
    quote: "A contract drafted with care is a dispute prevented. Every clause we write is a safeguard we build into your business relationship.",
    documents: [
      { name: "Development Agreement", desc: "Governs the relationship between a landowner and a developer for construction of a residential or commercial project. Defines development rights, sharing of built-up area or sale proceeds, obligations, timelines, and dispute resolution mechanisms." },
      { name: "Joint Venture Agreement", desc: "Joint ventures for property development or business collaborations require agreements that clearly define capital contribution, profit sharing, decision-making authority, exit mechanisms, and liability." },
      { name: "Service & Vendor Agreements", desc: "Protects both parties in contractor, service provider, or vendor relationships. Defines scope of work, payment terms, timelines, performance standards, confidentiality obligations, and termination provisions." },
      { name: "Non-Disclosure Agreement (NDA)", desc: "Protects your sensitive business information, trade secrets, and proprietary data when shared with potential partners, employees, or consultants. We draft both unilateral and mutual NDAs." },
      { name: "Memorandum of Understanding (MOU)", desc: "Records the mutual understanding and agreed terms of parties moving towards a business or property arrangement — before the final contract is executed. Creates a clear framework of expectations and demonstrates good faith." },
      { name: "Loan & Mortgage Agreements", desc: "Private lending arrangements require written agreements recording the loan amount, interest, repayment schedule, and security. We draft legally valid loan agreements and supporting mortgage or pledge documents." },
      { name: "Partnership & Business Agreements", desc: "Defines capital contributions, profit and loss sharing, management responsibilities, dispute resolution, and dissolution procedures — preventing ambiguity that can destabilise even long-standing business relationships." },
      { name: "Employment & Consultancy Agreements", desc: "Sets out terms of engagement, compensation, confidentiality obligations, intellectual property ownership, and post-engagement restrictions — protecting both the employer and the professional." },
    ],
    whatWeDo: [
      "Drafting of all commercial and business contracts",
      "Review and vetting of contracts prepared by other parties",
      "MOU preparation for property and commercial transactions",
      "Joint venture and partnership deed drafting",
      "NDA and confidentiality agreement preparation",
      "Contract negotiation support and advisory",
    ],
    process: [
      { step: "01", title: "Understanding Your Transaction", desc: "We begin with a thorough discussion of your business arrangement, relationship with the other party, and the specific outcomes you want the contract to achieve and protect." },
      { step: "02", title: "Legal Framework Assessment", desc: "We identify the applicable laws, regulatory requirements, and standard industry practices relevant to your contract — ensuring the document is compliant and enforceable." },
      { step: "03", title: "First Draft", desc: "A comprehensive first draft is prepared, covering all essential terms, conditions, representations, warranties, remedies, and dispute resolution mechanisms." },
      { step: "04", title: "Review & Negotiation Support", desc: "We walk you through every clause, explain the implications in plain language, and if required, assist in negotiations with the other party or their legal counsel." },
      { step: "05", title: "Finalisation & Execution", desc: "Once all terms are agreed, we finalise the document, advise on stamp duty implications, and assist with proper execution and, where applicable, registration." },
    ],
    timeline: "Simple agreements: 2–4 working days. Complex multi-party contracts or development agreements: 5–10 working days depending on negotiations.",
    docsRequired: [
      "Identity documents of all contracting parties",
      "Details of the transaction / business arrangement",
      "Any prior correspondence, term sheets, or LOIs",
      "Company incorporation documents (for entities)",
      "Relevant property documents (for property-related contracts)",
      "Any existing agreements being novated or amended",
    ],
  },,
  {
    slug: "pcntda-pmrda-transfers",
    title: "PCNTDA & PMRDA Transfers",
    subtitle: "Pimpri Chinchwad New Town Development Authority · Pune Metropolitan Region Development Authority",
    icon: "🏘️",
    shortDesc: "End-to-end assistance with property transfer matters under PCNTDA and PMRDA jurisdictions — ensuring compliance with the specific regulatory requirements of each authority.",
    overview: "Properties within the Pimpri Chinchwad New Town Development Authority (PCNTDA) and Pune Metropolitan Region Development Authority (PMRDA) areas are subject to specific regulatory frameworks that differ from standard municipal property transfers.\n\nThese jurisdictions have their own processes for approval of transfers, NOC requirements, stamp duty implications, and compliance requirements — and errors in navigating them can result in significant delays or rejected transactions.\n\nWith 24 years of practice serving clients in Pimpri Chinchwad and the wider PMRDA region, Advocate Anirudh Kamble provides expert guidance through every step of the transfer process.",
    quote: "Navigating PCNTDA and PMRDA transfers requires jurisdiction-specific expertise. We ensure your transaction proceeds smoothly and in full compliance.",
    whatWeDo: [
      "PCNTDA property transfer documentation and NOC assistance",
      "PMRDA jurisdiction property transfer guidance",
      "Agreement to Sale and Sale Deed drafting for PCNTDA/PMRDA properties",
      "Compliance review with applicable development authority rules",
      "Liaison with PCNTDA and PMRDA offices",
      "Stamp duty and registration guidance specific to these jurisdictions",
    ],
    process: [
      { step: "01", title: "Property & Jurisdiction Verification", desc: "We confirm the property's exact jurisdiction, applicable development authority, and the specific transfer rules and NOC requirements that apply." },
      { step: "02", title: "Document Review & Compliance Check", desc: "All existing title documents are reviewed for compliance with PCNTDA/PMRDA requirements, and any gaps or issues are identified before proceeding." },
      { step: "03", title: "NOC Application & Authority Liaison", desc: "We prepare and file all necessary NOC applications with the relevant development authority, and liaise with authority offices to facilitate timely processing." },
      { step: "04", title: "Drafting & Registration", desc: "Once NOCs and clearances are obtained, the transfer documents are drafted, properly stamped, and registered before the Sub-Registrar Office." },
    ],
    timeline: "NOC processing time varies — typically 15–45 working days depending on the authority and completeness of documentation. Total transfer process: 4–10 weeks.",
    docsRequired: [
      "Original allotment letter or prior sale/transfer documents",
      "Identity proof of transferor and transferee",
      "No-dues certificate from development authority",
      "Society NOC (if applicable)",
      "Approved building plan and occupancy certificate",
      "Property tax receipts",
      "Encumbrance Certificate",
    ],
  },,
  {
    slug: "deemed-conveyance",
    title: "Deemed Conveyance",
    subtitle: "For Cooperative Housing Societies in Pune & Pimpri Chinchwad",
    icon: "🏢",
    shortDesc: "Expert handling of deemed conveyance proceedings for housing societies — ensuring clear and legally sound transfer of land and building rights from developers to cooperative housing societies.",
    overview: "Thousands of cooperative housing societies in Pune and Pimpri Chinchwad have not received the conveyance of their land and building from the original developer — meaning the society does not legally own the plot on which its building stands.\n\nUnder the Maharashtra Cooperative Societies Act and the Maharashtra Ownership of Flats Act (MOFA), housing societies can apply to the Competent Authority (District Deputy Registrar) for Deemed Conveyance — obtaining legal title even without the developer's cooperation.\n\nThis is a complex, multi-stage legal process that requires precise documentation, knowledge of the applicable procedure, and effective liaison with the Competent Authority. Advocate Anirudh Kamble has extensive experience guiding housing societies through this process from start to finish.",
    quote: "Every housing society deserves legal title to the land it stands on. We ensure your society secures that right.",
    whatWeDo: [
      "Assessment of society's eligibility for Deemed Conveyance",
      "Preparation and filing of application to Competent Authority",
      "Compilation of all required documentation",
      "Representation before the Competent Authority",
      "Coordination with society members and managing committee",
      "Registration of the final Conveyance Deed",
    ],
    process: [
      { step: "01", title: "Eligibility Assessment", desc: "We assess the society's documents, building records, and existing agreements to confirm eligibility and identify any issues that may need resolution before filing." },
      { step: "02", title: "Document Compilation", desc: "We compile all required documents — society registration, member list, building approvals, title documents, and prior agreements — into a complete application file." },
      { step: "03", title: "Application to Competent Authority", desc: "The application for Deemed Conveyance is drafted and filed before the District Deputy Registrar (Competent Authority), along with all supporting documentation." },
      { step: "04", title: "Hearings & Representations", desc: "We represent the society through all hearings before the Competent Authority, respond to any objections, and ensure the proceedings move forward efficiently." },
      { step: "05", title: "Order & Registration", desc: "On receipt of the Deemed Conveyance order, we prepare and register the final Conveyance Deed before the Sub-Registrar Office — completing the legal title transfer to the society." },
    ],
    timeline: "Typically 3–9 months from filing to final registration, depending on the Competent Authority's schedule and any objections raised by the developer.",
    docsRequired: [
      "Society registration certificate",
      "List of members with their agreement copies",
      "Original sale agreements of all flat owners",
      "Approved building plans and commencement certificate",
      "Occupation certificate",
      "7/12 Extract or Property Card in developer's name",
      "Society's share certificates",
      "Correspondence with the developer regarding conveyance",
    ],
  },,
  {
    slug: "litigation-support",
    title: "Property & Contract Litigation",
    subtitle: "Title Disputes · Specific Performance · Injunctions · Breach of Contract · Landlord-Tenant Matters",
    icon: "🏛️",
    shortDesc: "Legal representation and advisory in property and contractual disputes before courts. Continuity of legal support from documentation to dispute resolution, safeguarding client interests at every stage.",
    overview: "Property and contract disputes can arise even from well-documented transactions — and when they do, you need a legal representative who combines deep documentation expertise with effective courtroom strategy.\n\nAdvocate Anirudh Kamble provides focused legal representation in property title disputes, breach of contract suits, specific performance actions, injunctions, and landlord-tenant matters before courts and tribunals in Pune and Pimpri Chinchwad.\n\nOur preventive-first practice means we have often prepared the very documentation at the heart of a dispute — giving us unique insight into the factual and legal position from the outset.",
    quote: "Strong documentation today is the best protection against disputes tomorrow. But when disputes arise, we are prepared to defend your position at every stage.",
    whatWeDo: [
      "Legal representation in property title disputes",
      "Specific performance suits for Agreement to Sale",
      "Injunction applications — temporary and permanent",
      "Breach of contract suits and recovery actions",
      "Landlord-tenant disputes and eviction proceedings",
      "Advisory on pre-litigation settlement options",
    ],
    process: [
      { step: "01", title: "Case Assessment & Legal Opinion", desc: "We begin with a thorough review of all relevant documents, facts, and legal issues — providing you with a clear and honest assessment of your legal position and realistic outcomes." },
      { step: "02", title: "Pre-Litigation Strategy", desc: "Where possible, we explore negotiated settlement, mediation, or notice-based resolution — saving time and costs before formal legal proceedings are initiated." },
      { step: "03", title: "Filing & Court Proceedings", desc: "If litigation is necessary, we prepare and file all required pleadings, applications, and supporting documents — and represent you effectively through every stage of the proceedings." },
      { step: "04", title: "Evidence & Arguments", desc: "We compile all documentary evidence, prepare witnesses, and present well-structured arguments before the court — ensuring your case is presented with maximum legal force." },
      { step: "05", title: "Judgement & Execution", desc: "After judgement, we assist with any execution proceedings, appeals if necessary, and ensure the final order is fully and effectively implemented in your favour." },
    ],
    timeline: "Civil suits in Pune typically take 1–3 years depending on complexity. Injunction applications may be heard within days to weeks. We keep you informed at every stage.",
    docsRequired: [
      "All title documents and agreements related to the dispute",
      "Correspondence, notices, and communications between parties",
      "Prior court orders or proceedings (if any)",
      "Payment receipts, bank records, or financial documents",
      "Witness details and contact information",
      "Any valuation reports or expert assessments",
    ],
  },
];

export const serviceGroups = [
  {
    title: "Property Documentation",
    desc: "70% of practice",
    items: ["property-documentation-registration", "deemed-conveyance", "title-search-due-diligence", "pcntda-pmrda-transfers"],
  },
  {
    title: "Commercial Contracts",
    desc: "20% of practice",
    items: ["contract-commercial-drafting"],
  },
  {
    title: "Notary & Consultation",
    desc: "10% of practice",
    items: ["litigation-support"],
  },
];
